### ISSUE TITLE
doc: move over Mastoton guide

### ISSUE THREAD

**Issue by HenryQW** [RSS3-Network/Docs#9]
Move to `/guide/operator/deployment/mastodon`

**Comment by brucexc** [comment]
In https://github.com/RSS3-Network/Node/pull/600, it is no longer necessary to deploy a Mastodon instance to support the worker startup. Instead, the worker supporting Mastodon has been implemented as a relay server. Therefore, there is no need to explain this separately in the docs. Instead, please add the relevant configuration instructions for `component.federated` in the corresponding section of `/guide/operator/deployment/guide.mdx` to help operators quickly start this worker. @FrankLi123

**Comment by FrankLi123** [comment]
Please review the PR: https://github.com/RSS3-Network/Docs/pull/20
